apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260525-135114-ez0vaw0ot1sc-service
spec:
  selector:
    app: enterprise-system-20260525-135114-ez0vaw0ot1sc
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
